import "./globals.css";
import { fontVariables } from "../lib/fonts";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontVariables} antialiased max-w-screen bg-primary-parchment`}>
        <NavBar />
        <div className="h-[70px]" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
